[build]
  # Base directory (root of the repository)
  base = "."
  # Build command for Netlify
  command = "npm run build"
  # Directory to publish
  publish = "dist"

[build.environment]
  # Frontend Environment Variables for Netlify
  VITE_APP_NAME = "The11EximOverSeas Ventures"
  VITE_APP_VERSION = "1.0.0"
  VITE_CONTACT_EMAIL = "the11eximoverseas@gmail.com"
  VITE_CONTACT_PHONE_PRIMARY = "+91 9617270009"
  VITE_CONTACT_PHONE_SECONDARY = "+91 9993006125"
  VITE_ENABLE_ANALYTICS = "true"
  VITE_ENABLE_DEBUG = "false"
  VITE_GOOGLE_MAPS_API_KEY = "AIzaSyDoy4xd7POgSrkLzxi8Z3b5DT4nrDA-zmw"
  VITE_DOMAIN = "www.the11eximoverseas.com"

[[redirects]]
  # Handle client-side routing
  from = "/*"
  to = "/index.html"
  status = 200

[context.production]
  # Production-specific settings
  command = "npm run build"

[context.deploy-preview]
  # Deploy preview settings
  command = "npm run build"

[context.branch-deploy]
  # Branch deploy settings
  command = "npm run build"

# Custom domain configuration
[context.production.environment]
  VITE_DOMAIN = "the11eximoverseas.com"
  VITE_CANONICAL_URL = "https://the11eximoverseas.com"